name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.33.0-focal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |          
          npm ci
          npm run pretest
          echo "Run playwright tests"
          npm run test:ci

